name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
     # - name: Initialize Testing Stack
     #   run: docker compose up -d
        
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip cryptography
    
      - name: Generate Supabase signing key
        run: python supabase/generate_signing_key.py

      - name: Supabase Testing Stack
        run: supabase start

      - name: Test
        run: dotnet test --no-restore
